# 1
CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE AUTOR(
    FECHA_NACIMIENTO DATETIME,
    NACIONALIDAD VARCHAR(100),
    NOMBRE VARCHAR(100) PRIMARY KEY
);

CREATE TABLE LIBRO(
  TITULO VARCHAR(100) PRIMARY KEY,
  PAGINAS INTEGER,
  IDIOMA VARCHAR(100),
  NOMBRE VARCHAR(100),
  FOREIGN KEY (NOMBRE) REFERENCES AUTOR(NOMBRE)
);

CREATE TABLE EDICION(
  AÑO DATE,
  ISBN VARCHAR(100) PRIMARY KEY,
  TITULO VARCHAR(100),
  FOREIGN KEY (TITULO) REFERENCES LIBRO(TITULO)
);

CREATE TABLE COPIA(
  NUMERO INTEGER PRIMARY KEY,
  ALQUILER FLOAT,
  ISBN VARCHAR(100),
  FOREIGN KEY (ISBN) REFERENCES EDICION(ISBN)
);

CREATE TABLE USUARIO(
    DNI VARCHAR(100) PRIMARY KEY ,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    DOMICILIO VARCHAR(100),
    NUMERO INTEGER,
    FOREIGN KEY (NUMERO) REFERENCES COPIA(NUMERO)
);

# 2
