/*
 Developers: Lorena Valle & Christian Hernandez
*/

package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"os"
	"strings"
)

type Autogenerated struct {
	Sentences []struct {
		Trans              string `json:"trans"`
		Orig               string `json:"orig"`
		Backend            int    `json:"backend"`
		ModelSpecification []struct {
		} `json:"model_specification"`
		TranslationEngineDebugInfo []struct {
			ModelTracking struct {
				CheckpointMd5 string `json:"checkpoint_md5"`
				LaunchDoc     string `json:"launch_doc"`
			} `json:"model_tracking"`
		} `json:"translation_engine_debug_info"`
	} `json:"sentences"`
	Src        string  `json:"src"`
	Confidence float64 `json:"confidence"`
	Spell      struct {
	} `json:"spell"`
	LdResult struct {
		Srclangs            []string `json:"srclangs"`
		SrclangsConfidences []int    `json:"srclangs_confidences"`
		ExtendedSrclangs    []string `json:"extended_srclangs"`
	} `json:"ld_result"`
}

func main() {

	scanner := bufio.NewScanner(os.Stdin)

	var in = flag.String("in", "es", "")
	var out = flag.String("out", "en", "")
	var text string

	flag.Parse()

	fmt.Println("text to translate")
	scanner.Scan()
	text = scanner.Text()

	textp := strings.ReplaceAll(text, " ", "%20")

	url := fmt.Sprintf("https://translate.google.com/translate_a/single?client=at&dt=t&dt=ld&dt=qca&dt=rm&dt=bd&dj=1&hl=es-ES&ie=UTF-8&oe=UTF-8&inputm=2&otf=2&iid=1dd3b944-fa62-4b55-b330-74909a99969e&sl=%s&tl=%s&text=%s&op=translate", *in, *out, textp)

	req, _ := http.NewRequest("GET", url, nil)

	req.Header.Add("cookie", "NID=220%3DlYz-AzlXlO_NmlsBVklPxQC4wBSTLGO9c3EsMpfQCh3yWFOcXrYRfUPehd7VU4xaXP7BW2QgMlJgCkvGkLyH9GKobeCrCDhNJudu60nGC32yPPUnm55OXKPHbIZJd6tuWM1vKXwuYayCDMpEi7oSlvzQvQew8aSQreoT3VgjkX8")

	res, _ := http.DefaultClient.Do(req)

	var data Autogenerated

	json.NewDecoder(res.Body).Decode(&data)

	fmt.Println(data.Sentences[0].Trans)
}
