package database

const (
	INSERT_EQUIPO       = "INSERT INTO EQUIPO(NOMBRE, CAMPEONATOS, ENCARGADO) VALUES "
	INSERT_PATROCINADOR = "INSERT INTO PATROCINADOR(NOMBRE, SEDE, TAMAÑO) VALUES "
	INSERT_EVENTO       = "INSERT INTO EVENTO(NOMBRE, FECHA, LUGAR) VALUES "
	INSERT_DEPORTE      = "INSERT INTO DEPORTE(NOMBRE, TIPO, AREA_ESPECIALIZADA) VALUES "
	INSERT_E2           = "INSERT INTO EQUIPO_PATROCINADOR(ID_EQUIPO, ID_PATROCINADOR, VIGENCIA, INVERSION) VALUES "
	INSERT_ATLETA       = "INSERT INTO ATLETA(NOMBRE, EDAD, SALARIO, ID_EQUIPO) VALUES"
	INSERT_E3           = "INSERT INTO EQUIPO_DEPORTE(ID_EQUIPO, ID_DEPORTE, FUNDACION, SEDE) VALUES "
	INSERT_RES          = "INSERT INTO RESULTADO(PUNTUACION, TIEMPO, FECHA, ID_EVENTO, ID_EQUIPO) VALUES "
)
