CREATE DATABASE EC1_WEB;
USE EC1_WEB;

CREATE TABLE USER(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    EDAD VARCHAR(100),
    CONTRASE VARCHAR(100)
);

