version: '3'

services:
  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: upemor 
      POSTGRES_PASSWORD: lobos_rojos
      POSTGRES_DB: asistencia
    volumes:
      - ./data:/var/lib/postgresql/
